import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import { useCursorContext } from '../../context/CursorContext';
import { CustomCursor } from "../";

const Layout = ({ children }) => {
    const { handleMoveCursor } = useCursorContext();

    return (
        <>  
            <Head>
                <title>using socket.io with nextjs</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main
                onMouseMove={handleMoveCursor}
            >
                {children}
            </main>
            <CustomCursor />
            <Toaster position="bottom-center" gutter={56} />
        </>
    )
}
export default Layout;