import Head from 'next/head';
import { Toaster } from 'react-hot-toast';

const Layout = ({ children }) => {
    return (
        <>  
            <Head>
                <title>using socket.io with nextjs</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                {children}
            </main>
            <Toaster position="bottom-center" gutter={56} />
        </>
    )
}
export default Layout;