import Head from 'next/head';

const Layout = ({ children }) => {
    return (
        <>  
            <Head>
                <title>using socket.io with nextjs</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                {children}
            </main>
        </>
    )
}
export default Layout;