import { useEffect, useState } from 'react';
import Head from 'next/head';
import io from 'socket.io-client';

let socket = false;

const Home = () => {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");

  useEffect(() => {
    if(!socket) {
      socket = io(`${process.env.NEXT_PUBLIC_SOCKET_URL}`);
    }
  }, []);

  useEffect(() => {
    socket.on('chat', (msg) => {
      setMessages([...messages, msg]);
    })
  }, [messages]);

  const sendMessage = () => {
    socket.emit('chat', input);
    setInput('');
  }

  return (
    <div>
      <Head>
        <title>using socket.io with nextjs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Socket.io + Next.js chat app</h1>

      <input type="text" placeholder="message" onChange={e => setInput(e.target.value)} value={input}/>
      <button onClick={sendMessage}>send</button>

      <div id="messages">
        {
          messages.map(msg => {
            <div class="message">
              <p>{msg}</p>
            </div>
          })
        }
      </div>
    </div>
  )
}
export default Home;